### ISSUE TITLE
CI tests are failling

### ISSUE THREAD

**Issue by wiederm** [Exscientia/StableNetGuardOwl#31]
The CI tests are failing for main with the following [error](https://github.com/Exscientia/StableNetGuardOwl/actions/runs/9385882164/job/25845108233):

```
    import molflux.datasets
../../../micromamba-root/envs/test/lib/python3.12/site-packages/molflux/datasets/__init__.py:14: in <module>
    fill_catalogue()
../../../micromamba-root/envs/test/lib/python3.12/site-packages/molflux/datasets/catalogue.py:28: in fill_catalogue
    for namespace, entrypoints in entry_points().items()
E   AttributeError: 'EntryPoints' object has no attribute 'items'
```

@adambaskerville , have you seen this before?

**Comment by adambaskerville** [comment]
Discussed on slack but just for future reference and for users or anyone searching from Google who needs a fix:

The issue is not explicitly with `molflux` but with `importlib` used with Python 3.12. See the `importlib` command here called in `molflux`:

https://github.com/Exscientia/molflux/blob/main/src/molflux/datasets/catalogue.py#L5

which is called on line 28 and flags the `items()` error. It might be the case that `importlib` of more specifically `importlib_metadata` for Python 3.12 has had a syntax change? Molflux is only checked against 3.8-3.11. My working conda environment which uses Python 3.11 uses `importlib_metadata='4.13.0'`
